### ISSUE TITLE
The repo needs a quick introduction 

### ISSUE THREAD

**Issue by FahadLive** [wizguin/yukon#21]
The README file lacks a quick summary/intro. Also, consider adding a description. It would help other people on the web! :)

**Comment by indexxing** [comment]
I feel like the README is pretty good, it could use some more downloading explanation but other than that it seems fine. Though, I do wish a wiki was added so you could quickly see stuff like adding items, rooms, or other stuff if you don't already know how. I've never used GitHub Wikis and I don't see them very often, so they may be paid I don't know.

**Comment by FahadLive** [comment]
Oh yeah, README seems fine now. As a side note, I myself haven't used wiki either....
