### ISSUE TITLE
Uncaught TypeError: t is undefined

### ISSUE THREAD

**Issue by littlegrosslittleguy** [wizguin/yukon#22]
The game completely crashes when logging in, right as the room is loading. It freezes on the loading screen with the animation stopping. 
![Screenshot 2024-08-05 024239](https://github.com/user-attachments/assets/eac63ffe-d427-48f6-af9d-2c227c48de1d)

The server, proxies, and registration service appears to work fine. Occurs on both Firefox and Chromium-based browsers, even after multiple builds and an isolated localhost test server.

The full error:
![Screenshot 2024-08-05 024529](https://github.com/user-attachments/assets/28b1fd50-3e4f-45ff-bd28-e50de5babd40)

**Comment by tomas-correia** [comment]
Does this happen in dev mode?

**Comment by littlegrosslittleguy** [comment]
> Does this happen in dev mode?

Yes, it does. Both dev mode and built.

**Comment by littlegrosslittleguy** [comment]
Testing again on a Chromium-based browser, the error has a slightly different message, but it comes from the same sources.
![Screenshot 2024-08-05 224003](https://github.com/user-attachments/assets/29a29c21-45a4-40cc-90c8-76b03f35e023)

**Comment by sky-is-winning** [comment]
this is a physics issue. check your physics file

**Comment by littlegrosslittleguy** [comment]
> this is a physics issue. check your physics file

Odd, since I only cloned the assets from the official repo. Here's my Town physics file. [town-physics.json](https://github.com/user-attachments/files/16552336/town-physics.json)

**Comment by sky-is-winning** [comment]
> > this is a physics issue. check your physics file
> 
> Odd, since I only cloned the assets from the official repo. Here's my Town physics file. [town-physics.json](https://github.com/user-attachments/files/16552336/town-physics.json)

Looks to me like you're missing some assets. Check they're being served correctly or reclone the assets from https://gitgud.io/piefruit/assets

**Comment by littlegrosslittleguy** [comment]
> > > this is a physics issue. check your physics file
> > 
> > 
> > Odd, since I only cloned the assets from the official repo. Here's my Town physics file. [town-physics.json](https://github.com/user-attachments/files/16552336/town-physics.json)
> 
> Looks to me like you're missing some assets. Check they're being served correctly or reclone the assets from https://gitgud.io/piefruit/assets

That fixed it; it seems the _PenguinSauce_ repository (that I was using) is outdated.
