### ISSUE TITLE
Assets page not found

### ISSUE THREAD

**Issue by wildmaster84** [wizguin/yukon#3]
Is there a new link for the assets because I get page not found??

**Comment by wildmaster84** [comment]
Found it in the discord server

**Comment by masasidan** [comment]
where did you find it? i'm facing the same problem.

**Comment by wildmaster84** [comment]
> where did you find it? i'm facing the same problem.

Check Pins In The Server

**Comment by JohnB17** [comment]
Discord server is gone, does anyone have the link?
