### ISSUE TITLE
Running npm run dev gives error npm ERR! Invalid version: "1.3-beta"

### ISSUE THREAD

**Issue by zahin45** [wizguin/yukon#4]
`root@:~/yukon# npm run dev
npm ERR! Invalid version: "1.3-beta"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-12T23_57_16_200Z-debug.log
`
![image](https://user-images.githubusercontent.com/67522617/168189639-66429d2b-7493-4ed2-bd2a-2190753789e2.png)

**Comment by wizguin** [comment]
Fixed in #5
